---

- 
  name: Terminate every running instance in a region. Use with EXTREME caution.
  become: true
  connection: local
  hosts: localhost
  vars_files:
             - ../aws_vars/vars
  tasks:
      - name: "Delete AWS instances"
        community.aws.ec2_instance:
                   region: "{{ aws_region }}"
                   state: absent
                   filters:
                       instance-state-name: running
